package crash

import (
	"fmt"
	"github.com/docker/docker/pkg/reexec"
	"github.com/pkg/errors"
	"github.com/ssst0n3/awesome_libs/awesome_error"
	"github.com/ssst0n3/awesome_libs/log"
	"os"
)

const ExpName = "crash"

func init() {
	reexec.Register(ExpName, Exploit)
}

func InvokeExploit() (err error) {
	cmd := reexec.Command(ExpName)
	log.Logger.Debug(cmd.Path)
	cmd.Stderr = os.Stderr
	cmd.Stdout = os.Stdout

	if err := cmd.Run(); err != nil {
		err = errors.Wrap(err, fmt.Sprintf("%s error on re-exec cmd", ExpName))
		awesome_error.CheckErr(err)
		return err
	}
	return
}
